git clone https://github.com/pp285/pp /mnt/user/D2RS-2025spring/pp --depth 1
git clone https://github.com/fas20052/414.ybdt-hzau /mnt/user/D2RS-2025spring/414.ybdt-hzau --depth 1
git clone https://github.com/ABEL-L76/gaolab /mnt/user/D2RS-2025spring/gaolab --depth 1
git clone https://github.com/chen5210311/Group-exam /mnt/user/D2RS-2025spring/Group-exam --depth 1
git clone https://github.com/shusuh-pop/zihuan24-hzau /mnt/user/D2RS-2025spring/zihuan24-hzau --depth 1
git clone https://github.com/luzhaohan/lu-hzau /mnt/user/D2RS-2025spring/lu-hzau --depth 1
git clone https://github.com/BookTotle/website-sanpu /mnt/user/D2RS-2025spring/website-sanpu --depth 1
git clone https://github.com/crx2024/crx-lab /mnt/user/D2RS-2025spring/crx-lab --depth 1
git clone https://github.com/jayzky/soil-mapping /mnt/user/D2RS-2025spring/soil-mapping --depth 1
git clone https://github.com/lee1234567843/No.53-Website-Construction-for-Research-Groups /mnt/user/D2RS-2025spring/No.53-Website-Construction-for-Research-Groups --depth 1
git clone https://github.com/crr343/wc-lab /mnt/user/D2RS-2025spring/wc-lab --depth 1
git clone https://github.com/Apollo-z/I-can-see-I-can-get-there /mnt/user/D2RS-2025spring/I-can-see-I-can-get-there --depth 1
git clone https://github.com/syz357/NO.55-exam /mnt/user/D2RS-2025spring/NO.55-exam --depth 1
git clone https://github.com/mikk123123/No.44-ecological-civilization /mnt/user/D2RS-2025spring/No.44-ecological-civilization --depth 1
git clone https://github.com/ha-hug/Reproducing-2024imate-zhou /mnt/user/D2RS-2025spring/Reproducing-2024imate-zhou --depth 1
git clone https://github.com/jung-7-beep/Echo /mnt/user/D2RS-2025spring/Echo --depth 1
git clone https://github.com/7352Mengyuan/Huanjingsf /mnt/user/D2RS-2025spring/Huanjingsf --depth 1
git clone https://github.com/kk11985/69_Website-construction /mnt/user/D2RS-2025spring/69_Website-construction --depth 1
git clone https://github.com/xuexue-chen/Hulab-hazu /mnt/user/D2RS-2025spring/Hulab-hazu --depth 1
git clone https://github.com/Liting-shu/group51-website-construction /mnt/user/D2RS-2025spring/group51-website-construction --depth 1
git clone https://github.com/hunie233/link /mnt/user/D2RS-2025spring/link --depth 1
git clone https://github.com/ningcaier/huhqandliuj-lab /mnt/user/D2RS-2025spring/huhqandliuj-lab --depth 1
git clone https://github.com/ykyh28/Houjt-hzau /mnt/user/D2RS-2025spring/Houjt-hzau --depth 1
git clone https://github.com/123S-OSS/website-introduction-239 /mnt/user/D2RS-2025spring/website-introduction-239 --depth 1
git clone https://github.com/JYQ-123/plant-nitrition /mnt/user/D2RS-2025spring/plant-nitrition --depth 1
git clone https://github.com/D2RS-2025spring/wyr_group /mnt/user/D2RS-2025spring/wyr_group --depth 1
git clone https://github.com/wss0910/website-construction /mnt/user/D2RS-2025spring/website-construction --depth 1
git clone https://github.com/shuaige12581/wyc-group /mnt/user/D2RS-2025spring/wyc-group --depth 1
git clone https://github.com/Zhao-kai111/liulab-hzau /mnt/user/D2RS-2025spring/liulab-hzau --depth 1
git clone https://github.com/eatch16/Listeria_ForestView /mnt/user/D2RS-2025spring/Listeria_ForestView --depth 1
git clone https://github.com/zhou125910/SDVSN /mnt/user/D2RS-2025spring/SDVSN --depth 1
git clone https://github.com/hzauym/AI-navigation-website /mnt/user/D2RS-2025spring/AI-navigation-website --depth 1
git clone https://github.com/YanWanYing/nitrogen-recovery /mnt/user/D2RS-2025spring/nitrogen-recovery --depth 1
git clone https://github.com/6-NanCheng/Rect2PPT /mnt/user/D2RS-2025spring/Rect2PPT --depth 1
git clone https://github.com/unrestraint1/Phosphorus-in-Watershed /mnt/user/D2RS-2025spring/Phosphorus-in-Watershed --depth 1
git clone https://github.com/D2RS-2025spring/ForestView_dstNET_group54 /mnt/user/D2RS-2025spring/ForestView_dstNET_group54 --depth 1
git clone https://github.com/m1st0917/zj-lab /mnt/user/D2RS-2025spring/zj-lab --depth 1
git clone https://github.com/lyf123456654321/data-reproduction43 /mnt/user/D2RS-2025spring/data-reproduction43 --depth 1
git clone https://github.com/xi-kexin/lxw-lab /mnt/user/D2RS-2025spring/lxw-lab --depth 1
git clone https://github.com/ytt871258130/environment-lab /mnt/user/D2RS-2025spring/environment-lab --depth 1
git clone https://github.com/BenLester16/cpgroup-lab /mnt/user/D2RS-2025spring/cpgroup-lab --depth 1
git clone https://github.com/BenLester16/cpgroupsyfx /mnt/user/D2RS-2025spring/cpgroupsyfx --depth 1
git clone https://github.com/14hg-D/Lab-of-Soil-Mineral-and-Environment /mnt/user/D2RS-2025spring/Lab-of-Soil-Mineral-and-Environment --depth 1
git clone https://github.com/sxy0326/webgis_GF.github.io /mnt/user/D2RS-2025spring/webgis_GF.github.io --depth 1
git clone https://github.com/Spade-Atek/ANSPAnalytics /mnt/user/D2RS-2025spring/ANSPAnalytics --depth 1
git clone https://github.com/caoxuhui1/26.Website-construction /mnt/user/D2RS-2025spring/26.Website-construction --depth 1
git clone https://github.com/Gmyue/NLTK-project /mnt/user/D2RS-2025spring/NLTK-project --depth 1
git clone https://github.com/hsywww/huronggui-lab /mnt/user/D2RS-2025spring/huronggui-lab --depth 1
git clone https://github.com/weare-lab/weekend-lad /mnt/user/D2RS-2025spring/weekend-lad --depth 1
git clone https://github.com/huaarui/Environmental-themed-Website /mnt/user/D2RS-2025spring/Environmental-themed-Website --depth 1
git clone https://github.com/GG10BOND/Guozl-lab /mnt/user/D2RS-2025spring/Guozl-lab --depth 1
git clone https://github.com/vidool/Campus-EcoNet /mnt/user/D2RS-2025spring/Campus-EcoNet --depth 1
git clone https://github.com/Liuhai626/LHlab-hzau /mnt/user/D2RS-2025spring/LHlab-hzau --depth 1
git clone https://github.com/hexinyu917/datareproduction13 /mnt/user/D2RS-2025spring/datareproduction13 --depth 1
git clone https://github.com/eybb25/chenc-lab /mnt/user/D2RS-2025spring/chenc-lab --depth 1
git clone https://github.com/R-yf/lu-lab /mnt/user/D2RS-2025spring/lu-lab --depth 1
git clone https://github.com/zhangyuandorr/lixk-lab /mnt/user/D2RS-2025spring/lixk-lab --depth 1
git clone https://github.com/sas12-bot/-ForestView /mnt/user/D2RS-2025spring/-ForestView --depth 1
git clone https://github.com/mortalccookiee/geotools /mnt/user/D2RS-2025spring/geotools --depth 1
git clone https://github.com/G-1988/tanzx-lab /mnt/user/D2RS-2025spring/tanzx-lab --depth 1
git clone https://github.com/coraluo/63lab-hzau /mnt/user/D2RS-2025spring/63lab-hzau --depth 1
git clone https://github.com/simplelity/xietong-s-machine-learning-forestview /mnt/user/D2RS-2025spring/xietong-s-machine-learning-forestview --depth 1
git clone https://github.com/Ming1209x/Max-lab /mnt/user/D2RS-2025spring/Max-lab --depth 1
git clone https://github.com/11-sansb/dingguangda-lab /mnt/user/D2RS-2025spring/dingguangda-lab --depth 1
git clone https://github.com/2024303110046/-Machine-Learning.ForestView /mnt/user/D2RS-2025spring/-Machine-Learning.ForestView --depth 1
git clone https://github.com/yv0610/ForestViz /mnt/user/D2RS-2025spring/ForestViz --depth 1
git clone https://github.com/xuexiaoshuai666/huangli-lab /mnt/user/D2RS-2025spring/huangli-lab --depth 1
git clone https://github.com/qazzjh/finalexam /mnt/user/D2RS-2025spring/finalexam --depth 1
git clone https://github.com/NTThome/wulab-hzau /mnt/user/D2RS-2025spring/wulab-hzau --depth 1
git clone https://github.com/ZhuzhPhloem/sunxc-lab /mnt/user/D2RS-2025spring/sunxc-lab --depth 1
