mv -v -- pp CodeLog
mv -v -- 414.ybdt-hzau ybdt-hzau
mv -v -- gaolab ClimaVision
mv -v -- Group-exam Jieqi24
mv -v -- zihuan24-hzau tanw-lab
mv -v -- lu-hzau PaperEcho-lu
mv -v -- website-sanpu sanpu
mv -v -- No.53-Website-Construction-for-Research-Groups fengx-lab
mv -v -- wc-lab wangc-lab
mv -v -- I-can-see-I-can-get-there robotMap
mv -v -- NO.55-exam PaperEcho
mv -v -- No.44-ecological-civilization Eco
mv -v -- Reproducing-2024imate-zhou PaperEcho-zhou
mv -v -- Echo TasteHub
mv -v -- Huanjingsf HubeiTrip
mv -v -- 69_Website-construction MusicChart
mv -v -- group51-website-construction BioFilmHub
mv -v -- link wanb-lab
mv -v -- website-introduction-239 MediTrack
mv -v -- wyr_group PaperEcho-wyr
mv -v -- website-construction jiangch-tour
mv -v -- wyc-group FeeQuant
mv -v -- Listeria_ForestView Listeria-ForestView
mv -v -- AI-navigation-website AI
mv -v -- nitrogen-recovery NitroRec
mv -v -- ForestView_dstNET_group54 DST-NET
mv -v -- data-reproduction43 data-reproduction
mv -v -- environment-lab liug-lab
mv -v -- Lab-of-Soil-Mineral-and-Environment wangx-lab
mv -v -- webgis_GF.github.io webgis_GF
mv -v -- 26.Website-construction SoloSite
mv -v -- weekend-lad lich-lab
mv -v -- Environmental-themed-Website ecological
mv -v -- LHlab-hzau LH-lab
mv -v -- datareproduction13 PaperEcho-liao
mv -v -- -ForestView ARIMAcast
mv -v -- 63lab-hzau luj-lab
mv -v -- xietong-s-machine-learning-forestview ForestView
mv -v -- -Machine-Learning.ForestView PaperEcho-ForestView
mv -v -- finalexam dingg-lab
mv -v -- wulab-hzau wus-lab
